### ISSUE TITLE
Resource should not send weak ETag in If-Match for delete or update

### ISSUE THREAD

**Issue by dchandekstark** [projecthydra/ldp#64]
Currently, LDP::Resource unconditionally adds an If-Match header to delete and update requests with the ETag from a previous GET, if available.  It should not add this header if the ETag is weak b/c HTTP PUT and DELETE require strong comparison when If-Match is present.

See also: https://github.com/fcrepo4/fcrepo4/pull/1089

/cc @escowles

**Comment by escowles** [comment]
We discussed this back in August, and decided the best thing to do was for the client to use `If-Unmodified-Since` instead of `If-Match`.

**Comment by cjcolvar** [comment]
This currently breaks fedora-migrate for fedora 4.6.0+.

**Comment by cjcolvar** [comment]
Fedora ticket suggesting If-Unmodified-Since instead of If-Match: https://jira.duraspace.org/browse/FCREPO-2122
